--확장 SQL
-- GROUP BY
SELECT * FROM EMP;

SELECT AVG(SAL),DEPTNO FROM EMP
GROUP BY DEPTNO;
--------------------------------------------------------------------
SELECT MAX(SAL),DEPTNO FROM EMP
GROUP BY DEPTNO
HAVING MAX(SAL) > 500;

--------------------------------------------------------------------
--DROP TABLE MYBOARD;
--SELECT * FROM MYBOARD;
CREATE TABLE MYBOARD(
NUM NUMBER(4) PRIMARY KEY,
AUTHOR VARCHAR2(12),
TITLE VARCHAR2(30),
CONTENT VARCHAR2(60)
);
CREATE SEQUENCE MYBOARD_SEQ;
--SELECT * FROM MYBOARD;

SELECT * FROM USER_SEQUENCES;
SELECT * FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'MYBOARD_SEQ';

SELECT MYBOARD_SEQ.NEXTVAL FROM DUAL;
--------------------------------------------------------------------
INSERT INTO MYBOARD(NUM,AUTHOR,TITLE,CONTENT)
VALUES(MYBOARD_SEQ.NEXTVAL,'철수','제목','내용이다.');
--1 행 이(가) 삽입되었습니다.
SELECT * FROM MYBOARD;





